### PR TITLE
Google cloud functions

### PR DESCRIPTION
**Pull request by trieloff**

### CODE REVIEW

**Comment by trieloff** [comment]
For package parameter support, it looks like we need https://cloud.google.com/security-key-management in the wrapper.

**Comment by trieloff** [comment]
Not yet ready-ready, but comments welcome.

**Review by tripodsan — APPROVED** [review]

**Comment by trieloff** [comment]
```bash
$ http https://us-central1-helix-225321.cloudfunctions.net/simple-package--simple-name_1_45_0/foo
HTTP/1.1 200 OK
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 125
Content-Type: text/plain; charset=utf-8
Date: Mon, 22 Feb 2021 11:16:15 GMT
Etag: W/"7d-pr/jlaWBNloeL8Vr0eGUyPfZEyY"
Foo: bar
Function-Execution-Id: 09w3zxsdfz79
Hey: ho
Server: Google Frontend
Surrogate-Key: simple
X-Cloud-Trace-Context: 48c23ba9fbcbf06665ee136479635ff6;o=1
X-Powered-By: Express

{
    "file": "Hello, world.\n",
    "url": "https://us-central1-helix-225321.cloudfunctions.net/simple-package--simple-name_1_45_0/foo"
}
```

check out the `Foo` and `Bar` headers, coming from action and package parameters.

**Comment by trieloff** [comment]
I just need to find out how to put the test credentials into CircleCI.

**Pull request merged**
