### PR TITLE
feat(aws): delete unused integrations

### LINKED ISSUE #128: AWS: update link should cleanup old integrations
each time helix deploy creates a new _link_, it also creates a new integration for that routes and the new function.
overtime this accumulates stale integrations that cause problems with the 300 integrations per API limit.

when linking, helix-deploy should also cleanup unused integrations

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #128

adds 2 new features:

#### cleans up releated integrations after linking

image

#### adds new command `-aws-cleanup-integrations` that deletes unused integrations

image
image

### CODE REVIEW

**Review by trieloff — COMMENTED** [review]
Is there a chance to test this in an integration test?

**Comment by tripodsan** [comment]
> Is there a chance to test this in an integration test?

hmm.... would be a bit tricky... as it need to create a new version and then link it.
we could increase the version of the simple action everytime...

**Comment by trieloff** [comment]
Or use the CI build number as the patch version number, so that we don't have to commit back.

**Comment by tripodsan** [comment]
> Or use the CI build number as the patch version number, so that we don't have to commit back.

yes. actually doing a `-l ci` should already cause a cleanup. we only need to catch it in a test.

**Comment by tripodsan** [comment]
@trieloff I added some check to the integration test.

**Comment by trieloff** [comment]
Merge away!

**Pull request merged**
